/*
 *  @FileName(文件名):  XXJJYSURLInterFace.m
 *  @ProjectName(工程名):   JJYSPlusPlus
 *  @CreateDate(创建日期):   Created by Wangguibin on 16/5/10.
 *  @Copyright(版权所有):     Copyright © 2016年 王贵彬. All rights reserved.
 */
#import "XXJJYSURLInterFace.h"

#pragma mark--参数的 Key
NSString *const KMethodName = @"methodName";              //方法名
NSString *const KVersion = @"version";                    //接口版本
NSString *const KList_order = @"list_order";              //排序参数列表
NSString *const KMobile = @"mobile";                      //手机号
NSString *const KCode = @"code";                          //验证码
NSString *const KYuchanqi = @"yuchanqi";                  //预产期
NSString *const KSign = @"sign";                          //动态签名
NSString *const KPredict_day = @"predict_day";            //预产期
NSString *const KPredict_day_more = @"predict_day_more";  //预产期后有档期
NSString *const KExperience = @"experience";              //经验
NSString  *const KLevel =@"level"; //等级
NSString *const KYear = @"year";                          //年龄
NSString *const KRegion = @"region";                      //籍贯
NSString *const KYuesao_id = @"yuesao_id";                //月嫂ID
NSString *const KUser_id = @"user_id";                    //用户ID
NSString *const kref_user_id = @"ref_user_id"; ///评论用户的id
NSString *const KUserName =@"username"; //用户名
NSString *const KNickname = @"nickname";                  //昵称
NSString*const KName = @"name"; //名字
NSString *const KAddress = @"address";                    //地址
NSString *const KArea =@"area"; //地区
NSString *const KProvice = @"provice";                    //省份
NSString *const KCity = @"city";                          //城市
NSString *const KTown = @"town";                          //镇区
NSString *const KDefault = @"default";                    //默认
NSString *const KAddress_id = @"address_id";
NSString *const kForce_desc = @"force_desc";              // 列表排序[1降序,0升序]
NSString *const kParentid   = @"parentid";                // 上级地址
NSString *const kContent   = @"content";                  // 内容
NSString *const kImage   = @"image[]";                    // 对月嫂评论图片
NSString *const kOrder_id = @"order_id";                  // 订单id
NSString *const kScore = @"score";                        // 主要分数
NSString *const kScore_extend = @"score_extend";          // 各项评分,用逗号分割
NSString *const kToken = @"token";                        // 用户指纹
NSString *const kOpenid_weixin = @"openid_weixin";        //openid_weixin
NSString *const kUnionid_weixin = @"unionid_weixin";        //unionid_weixin
NSString *const KDay_buy =@"day_buy";                      // 套餐
NSString *const KPhone =@"phone"; //手机号
NSString *const KSettle_date =@"settle_date";//预产期
NSString *const KScene_visit_id =@"scene_visit_id";//渠道id
NSString * const KPage =@"page";                            //页码
NSString *const Kis_buy =@"is_buy";
NSString *const Kask_id =@"ask_id";
NSString *const klist_order_revert =@"list_order_revert"; //翻转列表顺序
NSString *const kanswer_id =@"answer_id";
NSString *const kpid =@"pid";
NSString *const KSize =@"size";                             //每页多少
NSString *const kHeadphoto =@"headphoto";                   //头像
NSString *const kPredict_at =@"predict_at";                   //预产期
NSString *const kGender =@"gender";                         //性别[0未知1男2女]
NSString *const kCollect_id =@"collect_id";                         //收藏数据
NSString *const kId =@"id";                             //活动详情
NSString *const kchannel = @"channel";                   //支付渠道
NSString *const kextra_pay=@"extra_pay";//是否收取节假日费用
NSString *const kPredict_day = @"predict_day";                   //预产期
NSString *const kOrigin_id = @"origin_id";//来源
NSString *const kRand = @"rand";
NSString *const kJson =@"json";
NSString *const kSign = @"sign";
NSString *const kRefer_id = @"refer_id"; //前一张订单的order_id
NSString *const kSkiller_id = @"skiller_id"; ///育婴师的id
NSString *const kKeyword = @"keyword";

#pragma mark-- 参数的 Value
NSString *const KPlatform = @"platform";
NSString *const KPlatformValueIOS =@"2";
NSString *const KCityCode = @"citycode";
NSString *const KVsionValue = @"4.11";                   //接口版本号
NSString *const KYuesaoIndex = @"YuesaoIndex";        //月嫂列表
NSString *const KSmsCheckUser = @"SmsCheckUser";      //用户端短信校验
NSString *const KSmsLoginUser = @"SmsLoginUser";      //用户端登录校验
NSString *const KYuesaoView = @"YuesaoView";          //月嫂详情页
NSString *const KYuesaoHome = @"YuesaoHome";          //首页
NSString *const KYuesaoAbout = @"YuesaoAbout";        //关于页面
NSString *const KAddressUpdate = @"AddressUpdate";    //编辑地址
NSString *const KAddressInfo = @"AddressInfo";        //用户地址详情
NSString *const KAddressAdd = @"AddressAdd";          //添加地址
NSString *const KAddressDefault = @"AddressDefault";  //默认地址
NSString *const KAddressLast =@"AddressLast";//获取最后一条
NSString *const KAddressList = @"AddressList";        //地址列表
NSString *const KYuesaoSchedule = @"YuesaoSchedule";//月嫂档期
NSString *const KAddressAreainfo= @"AddressAreainfo";//地区信息
NSString *const KYuesaoCommentList=@"YuesaoCommentList"; //月嫂评论列表
NSString *const kYuesaoCommentInsert = @"YuesaoCommentInsert"; // 对月嫂评论
NSString *const kYuesaoScoreInsert = @"YuesaoScoreInsert";   // 对月嫂进行评分
NSString *const kOrderInsert = @"OrderInsert";                      // 对月嫂进行下单接口
NSString *const kOrderPayInfo = @"OrderPayInfo";                    //支付信息
NSString *const kOrderPayStart = @"OrderPayStart";                  //订单预支付
NSString *const kYuesaoCollectInsert = @"YuesaoCollectInsert";      //对月嫂进行关注
NSString *const kAppAbout = @"AppAbout";                            //关于家家
NSString *const kOrderIndex = @"OrderIndex";                        //订单列表
NSString *const kOrderInfo = @"OrderInfo";                          //订单详情
NSString *const kOrderWater = @"OrderWater";                        //订单流水
NSString *const kYuesaoCollectList = @"YuesaoCollectList";          //月嫂收藏列表
NSString *const kYuesaoConfig = @"YuesaoConfig";                    //用户端一次性配置是否强制更新
NSString *const kSchedule_day = @"predict_day";                    //预约日期
NSString *const kNum = @"num";                                      //宝宝个数
NSString *const kProduct_id = @"product_id";                        //服务id
NSString *const kRemark = @"remark";                                //其它要求
NSString *const kCoupon_id_user =@"coupon_id_user"; //优惠券id
NSString *const kProduct_days = @"product_days";
NSString *const kService_days = @"service_days";
NSString *const kTag = @"tag"; // 产品标签
NSString *const klevel_id =@"level_id"; //等级id
NSString	*const kpkg = @"pkg";
NSString *const kos_name = @"os_name";
NSString *const kos_version = @"os_version";

NSString *const kType = @"type";                                    //支付类型[1定金2尾款3全款]
NSString *const kUserInfo = @"UserInfo";                            //读取用户信息
NSString *const kUserLoginWeixin = @"UserLoginWeixin";              //微信登陆
NSString *const kYuesaoShowList = @"YuesaoShowList";                //工作风采
NSString *const kConfigServiceGroup = @"ConfigServiceGroup";        //产品种类 模型数组
NSString *const kConfigServiceDay = @"ConfigServiceDay"; // 配置购买天数
NSString *const kConfigProduct =@"ConfigProduct"; //新标准价格
NSString *const kHoliday = @"HolidayAll";
NSString *const kExpertAskList =@"ExpertAskList";
NSString *const kExpertAskView =@"ExpertAskView";
NSString *const kExpertList =@"ExpertList";
NSString *const kExpertAskAdd =@"ExpertAskAdd";
NSString *const kOrderPayExpertAsk=@"OrderPayExpertAsk";

NSString *const kVideoListCourse=@"VideoListCourse";
NSString *const kVideoCategory = @"VideoCategory";
NSString *const kVideoCommentListAction =@"VideoCommentList";

NSString *const kVideoCommentAdd =@"VideoCommentAdd";//视频加评论
NSString *const kVideoShare =@"VideoShare"; //视频分享
NSString *const kVideoView = @"VideoView";
NSString *const kvideo_course_id = @"video_course_id";
NSString *const kvideo_id =@"video_id";
NSString *const kQid =@"qid";
NSString *const krole =@"role";

NSString *const kUserInfoUpdate = @"UserInfoUpdate";                //修改用户信息
NSString *const kYuesaoCollectCancel = @"YuesaoCollectCancel";       //取消关注
NSString *const kActivityList = @"ActivityList";                     //活动列表
NSString *const kActivityInfo = @"ActivityInfo";                     //活动详情
NSString *const kOrderPrice = @"OrderPrice";                         //订单查价格
NSString *const kAppShare = @"AppShare";                             //月嫂分享
NSString *const kAddressYuesao = @"AddressYuesao";                   //月嫂的籍贯
NSString *const kOrderPayCancel = @"OrderPayCancel";                 //取消订单接口
NSString *const kOrderShare = @"OrderShare";                         //订单分享接口
NSString *const kAppleWelcome = @"AppleWelcome";                     //检测接口
NSString *const kWeixinBind = @"WeixinBind";                         //用户绑定微信
NSString *const kOpen_id = @"open_id";                               //微信open_id
NSString *const kplan_id = @"plan_id"; ///计划最小id
NSString *const kCouponList = @"CouponList";                         //优惠券列表
NSString *const kCouponFirsttime = @"CouponFirsttime";               //优惠券首次弹窗
NSString *const kCouponPwChange = @"CouponPwChange"; //兑换优惠券
NSString *const kYuesaoSearch = @"YuesaoIndex"; //月嫂搜索
NSString *const kAdvertBook =@"AdvertBook"; //预约提交资料
NSString *const kOrderScheduteCheck =@"OrderScheduteCheck";//下单档期检测
NSString *const kcategory_id =@"category_id";
NSString *const kMid = @"mid"; ///mid
NSString *const kID =@"id"; /// id
NSString *const kShareRule =@"ShareRule"; //分享规则 分享的APP
NSString *const kCount = @"count";                                   //优惠券评论总条数
NSString *const kCouponComment = @"CouponComment";                   //优惠券评论
NSString *const kCouponServiceGroup = @"CouponUserActive";         //优惠券适用列表
NSString *const kOrderPayChargeExtra = @"OrderPayChargeExtra";//附加费收取
NSString *const kOrderCheckUnpay =@"OrderCheckUnpay";//检测未付款订单
NSString *const kAdvertBookMsg =@"AdvertBookMsg" ; //报名信息
NSString *const kAdvertBookCount =@"AdvertBookCount";//报名人数
NSString *const kYuesaoVideo =@"YuesaoVideo"; //月嫂个人视频
NSString *const kDownOrderAddressID = @"kDownOrderAddressID"; //下单的地址id
NSString	*const kAdminOrderQcode =@"AdminOrderQcode"; //多笔尾款
NSString *const  kProductReorder = @"ProductReorder"; //续单时产品单价
NSString *const  kHolidayCheck = @"HolidayCheck"; //检查节假日
NSString *const kConfigReorder =@"ConfigReorder"; //续单天数列表
NSString *const kOrderInsertCuiru = @"OrderInsertCuiru"; //催乳服务下单
NSString *const kOrderPriceCuiru =@"OrderPriceCuiru"; //催乳价格
NSString *const kConfigProductCuiru = @"ConfigProductCuiru"; //催乳服务配置信息
NSString *const kArticleCategoryList =@"ArticleCategoryList"; ///文章分类
NSString *const kArticleList =@"ArticleList";  ///文章列表
NSString *const kArticleInfo =@"ArticleInfo";///文章详情

	///MARK:- 育婴师
NSString *const kSkillerYuyingIndex = @"SkillerYuyingIndex"; ///育婴师列表
NSString *const kSkillerYuyingView = @"SkillerYuyingView"; ///育婴师详情
NSString	*const kOrderInsertYuying =@"OrderInsertYuying" ; /// 育婴师下单
NSString *const kOrderPriceYuying = @"OrderPriceYuying"; ///育婴师下单价格
NSString *const kOrderPayInfoYuying = @"OrderPayInfoYuying"; /// 育婴师支付信息
NSString *const kOrderPayYuying = @"OrderPayYuying"; ///育婴师支付佣金
NSString *const kOrderPayPlanList = @"OrderPayPlanList"; ///育婴师月供列表
NSString	*const kOrderPayYuyingSalay = @"OrderPayYuyingSalay"; ///育婴师工资
NSString *const kSkillerYuyingSchedule = @"SkillerYuyingSchedule";//育婴师档期
NSString *const kSkillerYuyingSearch= @"SkillerYuyingSearch"; ///育婴师搜索
NSString *const kConfigCity = @"ConfigCity"; //配置城市
NSString *const kCorpList = @"CorpList"; // 加盟商列表
NSString	*const kYuesaoSchedulePie = @"YuesaoSchedulePie";
NSString *const kYuyingSchedulePie = @"YuyingSchedulePie";
NSString 	*const kArticleSearch = @"ArticleSearch";
NSString *const kAppHello = @"AppHello";
NSString *const kGuzngzhouComment = @"GuangzhouComment";
NSString *const kUserLoginInfo = @"UserLoginInfo";
NSString *const kArticleNiceList = @"ArticleNiceList";

NSString *const KUserShopniu = @"UserShopniu";       //远程登陆shopniu系统

